//
//  Data.m
//  Himnario Adventista
//
//  Created by Daniel Scholtus on 25/07/13.
//  Copyright (c) 2013 Daniel Scholtus. All rights reserved.
//

#import "Data.h"

@implementation Data

@synthesize title;
@synthesize content;

static NSArray *sharedItems = nil;

+ (NSArray *)items {
    return sharedItems;
}

+ (Data *)newItem:(NSArray *)strings {
    Data *lItem = [Data alloc];
    [lItem setTitle:strings[0]];
    [lItem setContent:strings[1]];
    return lItem;
}

+ (Data *)item:(NSIndexPath *)position {
    NSInteger lSection = position.section;
    NSInteger lRow = position.row;
    Data *lItem = sharedItems[lSection][1][lRow];
    return lItem;
}

+ (int)sections {
    int lSections = sharedItems.count;
    return lSections;
}

+ (int)itemsInSection:(int)section {
    NSArray *lSection = sharedItems[section][1];
    int lItems = lSection.count;
    return lItems;
}

+ (NSString *)titleForSection:(int)section {
    NSString *lTitle = sharedItems[section][0];
    return lTitle;
}

+ (void)initialize {
    if (!sharedItems){
        sharedItems = @[
                        @[@"Doctrina de Dios",
                          @[
                              [Data newItem:@[@"Nuestras creencias ...",@"A continuación presentamos las 28 creencias fundamentales que sostiene la Iglesia Adventista del Séptimo Día, y sus respectivos textos Bíblicos sobre los que se fundamentan las mismas. \n\nLos Adventistas del Séptimo Día aceptan la Biblia como su única regla de fe y apoyo seguro de las creencias fundamentales siendo éstas enseñanzas de las Santas Escrituras. \n\nEstas creencia, como se recogen más adelante, constituyen la comprensión de la enseñanza de la Escritura. \n\nLa revisión de estas declaraciones pueden ser hechas en el Congreso Mundial de la Asociación General de la Iglesia Adventista del Séptimo Día, cada cinco años, cuando la Iglesia es dirigida por el Espíritu Santo a una comprensión más completa de la verdad bíblica o si encuentra una mejor forma de expresar las enseñanzas de la Santa Palabra de Dios.",@"Fuente: http://adventistas.es/creeemos/nuestras-creencias/ \nFecha: 27 de Febrero de 2013"]],
                              [Data newItem:@[@"Las Santas Escrituras",@"Las Santas Escrituras, el Antiguo y el Nuevo Testamento, son la Palabra de Dios escrita, dada por inspiración divina por intermedio de santos hombres de Dios que hablaron y escribieron al ser movidos por el Espíritu Santo. \n\nEn esta Palabra, Dios ha transmitido al ser humano el conocimiento necesario para la Salvación. \n\nLas Santas Escrituras son la infalible revelación de la voluntad divina. \n\nSon la norma para el carácter, la prueba de la experiencia, la revelación autorizada de doctrinas, y el registro confiable de la actuación de Dios en la historia.",@"2 Pedro 1:20 y 21; \n2 Timoteo 3:16 y 17; \nSalmo 119:105; \nProverbios 30:5 y 6; \nIsaías 8:20; \nJuan 10:35; \nJuan 17:17; \n1 Tesalonicenses 2:13; \nHebreos 4:12."]],
                              [Data newItem:@[@"La Trinidad",@"Hay un solo Dios: Padre, Hijo y Espíritu Santo, una unidad de tres Personas coeternas. \n\nDios es inmortal, omnipotente, omnisciente, por encima de todo (trascendente), y siempre presente. \n\nEs infinito y está más allá de la comprensión humana, aunque es conocido por su revelación de sí mismo. \n\nEs eternamente digno de alabanza, adoración y servicio por toda la creación.",@"Deuteronomio 6:4; \nDeuteronomio 29:29; \nMateo 28:19; \n2 Corintios 13:14; \nEfesios 4:4&#8211;6; \n1 Pedro 1:2; \n1 Timoteo 1:17; \nApocalipsis 14:6 y 7."]],
                              [Data newItem:@[@"Dios Padre",@"Dios, el Eterno Padre, es el Creador, el Originador, el Sustentador y el Soberano de toda la creación. \n\nÉl es justo y santo, misericordioso y clemente, tardo en airarse, y grande en constante amor y fidelidad. \n\nLas cualidades y poderes mostrados en el Hijo y en el Espíritu Santo son, también, revelaciones del Padre.",@"Génesis 1:1; \nApocalipsis 4:11; \n1 Corintios 15:28; \nJuan 3:16; \n1 Juan 4:8; \n1 Timoteo 1:17: Éxodo 34:6 y 7; \nJuan 14:9."]],
                              [Data newItem:@[@"Dios Hijo",@"Dios, el Hijo Eterno, se encarnó en Jesucristo. \n\nPor medio de Él todas las cosas fueron creadas, se revela el carácter de Dios, se consuma la salvación de la humanidad y es juzgado el mundo. \n\nVerdadero Dios por siempre, también llegó a ser verdaderamente hombre, Jesús el Cristo. \n\nFue concebido por el Espíritu Santo, y nació de la virgen María. \n\nVivió y experimentó la tentación como ser humano, y ejemplificó perfectamente la justicia y el amor de Dios. \n\nA través de sus milagros demostró el poder de Dios y fue atestiguado como el Mesías prometido por Dios. \n\nJesús sufrió y murió voluntariamente en la cruz en nuestro lugar por nuestros pecados, fue resucitado de entre los muertos y ascendió para ministrar en el santuario celestial en nuestro favor. \n\nVendrá de nuevo en gloria para la liberación final de Su pueblo y la restauración de todas las cosas.",@"Juan 1:1&#8211;3 y14; \nColosenses 1:15&#8211;19; \nJuan 10:30; \nJuan 14:9; \nRomanos 5:18; \nRomanos 6:23; \n2 Corintios 5:17&#8211;19; \nJuan 5:22; \nLucas 1:35; \nFilipenses 2:5&#8211;11; \nHebreos 2:9&#8211;18; \n1 Corintios 15:3 y 4; \nHebreos 4:15; \nHebreos 7:25; \nHebreos 8:1 y 2; \nHebreos 9:28; \nJuan 14:1&#8211;3; \n1 Pedro 2:21; \nApocalipsis 22:20."]],
                              [Data newItem:@[@"Dios Espíritu Santo",@"Dios, el Espíritu Santo, desempeñó una parte activa con el Padre y el Hijo en la Creación, encarnación y redención. \n\nInspiró a los escritores de las Escrituras. \n\nLlenó la vida de Cristo con poder. \n\nLlama y convence a los seres humanos; y a aquellos que le responden, les renueva y transforma a la imagen de Dios. \n\nEnviado por el Padre y por el Hijo para permanecer para siempre con sus hijos, concede dones espirituales a la Iglesia, la capacita para dar testimonio de Cristo, y en armonía con las Escrituras, la guía a toda verdad.",@"Génesis 1:1 y 2; \nLucas 1:35; \nLucas 4:18; \nHechos 10:38; \n2 Pedro 1:21; \n2 Corintios 3:18; \nEfesios 4:11 y 12; \nHechos 1:8; \nJuan 14:16&#8211;18 y 26; \nJuan 15:26 y 27; \nJuan 16:7&#8211;13."]],
                              ]],
                              @[@"Doctrina del Hombre",
                                @[
                              [Data newItem:@[@"La Creación",@"Dios es el Creador de todas las cosas, y ha revelado en las Escrituras el auténtico relato de Su actividad creadora. \n\nEn seis días el Señor hizo “el cielo y la Tierra” y todo lo que tiene vida sobre la Tierra, y descansó el séptimo día de esa primera semana. \n\nDe este modo estableció el Sábado como un memorial permanente de su trabajo creativo completo. \n\nEl primer hombre y la primera mujer fueron creados a la imagen de Dios como coronación de la Creación, se les dio dominio sobre el mundo y se les dio la responsabilidad de cuidarlo. \n\nCuando el mundo fue terminado, era “muy bueno”, anunciando así la gloria de Dios.",@"Génesis 1 y 2; \nÉxodo 20:8&#8211;11; \nSalmo 19:1&#8211;6; \nSalmo 33:6 y 9; \nSalmo 104; \nHebreos 11:3; \nJuan 1:1&#8211;3; \nColosenses 1:16 y 17."]],
                              [Data newItem:@[@"La Naturaleza del Hombre",@"El hombre y la mujer fueron formados a imagen de Dios con individualidad, con el poder y la libertad de pensar y actuar. \n\nAunque fueron creados como seres libres, cada uno es una unidad indivisible de cuerpo, mente y espíritu, dependientes de Dios para la vida, el aliento y todo lo demás. \n\nCuando nuestros primeros padres desobedecieron a Dios, negaron su dependencia de Él y cayeron de su elevada posición bajo Dios. \n\nLa imagen de Dios en ellos fue desfigurada, pasando a estar sujetos a la muerte. \n\nSus descendientes comparten esa naturaleza caída y sus consecuencias. \n\nNacen con las debilidades y tendencias al mal. \n\nPero Dios en Cristo reconcilió consigo al mundo y a través de su Santo Espíritu restaura en los mortales penitentes la imagen de su Hacedor. \n\nCreados para la gloria de Dios, son llamados a amarle y amarse los unos a los otros, y cuidar del medio ambiente.",@"Génesis 1:26&#8211;28; \nGénesis 2:7; \nSalmo 8:4&#8211;8; \nHechos 17:24&#8211;28; \nGénesis 3; \nSalmo 51:5; \nRomanos 5:12&#8211;17; \n2 Corintios 5:19 y 20; \nSalmo 51:10; \n1 Juan 4:7&#8211;8, 11, 20; \nGénesis 2:15."]],
                              ]],
                        @[@"Doctrina de la Salvación",
                          @[
                              [Data newItem:@[@"El Gran Conflicto",@"Toda la humanidad está involucrada en un gran conflicto entre Cristo y Satanás, en cuanto al carácter de Dios, su Ley y su soberanía sobre el Universo. \n\nEse conflicto se originó en el Cielo, cuando un ser creado, dotado de libertad de elección, por exaltación propia se convirtió en Satanás, el adversario de Dios, y guió a la rebelión a una parte de los ángeles. \n\nÉl introdujo el espíritu de rebelión en este mundo cunado indujo a Adán y Eva a pecar. \n\nEl pecado de la humanidad distorsionó la imagen de Dios en el ser humano, el desorden en el mundo creado y su eventual devastación en el momento del diluvio mundial. \n\nObservado por toda la Creación, este mundo se convirtió en el escenario del conflicto universal, del cual será finalmente reivindicado el Dios de amor. \n\nPara asistir a su pueblo en esta controversia, Cristo envía su Santo Espíritu y ángeles leales para guiar, proteger, y sostenerlos en el camino de la Salvación.",@"Apocalipsis 12:4&#8211;9; \nIsaías 14:12&#8211;14; \nEzequiel 28:12&#8211;18; \nGénesis 3; \nRomanos 1:19&#8211;32; \nRomanos 5:19&#8211;21; \nRomanos 8:19&#8211;22; \nGénesis 6&#8211;8; \n2 Pedro 3:6; \n1 Corintios 4:9; \nHebreos 1:14."]],
                              [Data newItem:@[@"Vida, Muerte y Resurrección de Cristo",@"En la vida de Cristo, de perfecta obediencia a la voluntad de Dios, en su sufrimiento, muerte y resurrección, Dios proveyó el único medio de expiación del pecado humano, de modo que los que aceptan por fe esa expiación, puedan tener vida eterna, y toda la Creación comprenda mejor el infinito y santo amor del Creador. \n\nEsta perfecta expiación vindica la justicia de la ley de Dios y la gracia de su carácter; ya que a la misma vez, condena nuestros pecados, y hace provisión para nuestro perdón. \n\nLa muerte de Cristo es sustitutoria y expiatoria, reconciliando y transformando. \n\nLa resurrección de Cristo proclama el triunfo de Dios sobre las fuerzas del mal, y para aquellos que aceptan la expiación les asegura la victoria final sobre el pecado y la muerte. \n\nDeclara el señorío de Jesucristo, ante quien se doblará toda rodilla en el cielo y en la Tierra.",@"Juan 3:16; \nIsaías 53; \n1 Pedro 2:21&#8211;22; \n1 Corintios 15:3&#8211;4, 20&#8211;22; \n2 Corintios 5:14&#8211;15, 19&#8211;21; \nRomanos 1:4; \nRomanos 3:25; \nRomanos 4:25; \nRomanos 8:3&#8211;4; \n1 Juan 2:2; \n1 Juan 4:10; \nColosenses 2:15; \nFilipenses 2:6&#8211;11."]],
                              [Data newItem:@[@"La Experiencia de la Salvación",@"En infinito amor y misericordia, Dios permitió que Cristo, quien no conoció pecado, se convirtiese en pecado por nosotros, para que en Él fuésemos hechos justicia de Dios. \n\nGuiados por el Espíritu Santo sentimos nuestra necesidad, reconocemos nuestra pecaminosidad, nos arrepentimos de nuestras transgresiones y ejercemos fe en Jesús como Señor y Cristo, como Sustituto y Ejemplo. \n\nEsta fe que recibe la salvación, viene a través del poder de la Palabra y es el don de la gracia de Dios. \n\nPor medio de Cristo somos justificados, adoptados como hijos e hijas de Dios y libertados del dominio del pecado. \n\nPor medio del Espíritu, nacemos de nuevo y somos justificados. \n\nEl Espíritu renueva nuestra mente, escribe la ley de amor de Dios en nuestro corazón y se nos da el poder de vivir una vida santa. \n\nPermaneciendo en Él, llegamos a ser participantes de la naturaleza divina y tenemos la seguridad de la salvación, ahora y en el Juicio.",@"2 Corintios 5:17&#8211;21; \nJuan 3:16; \nGálatas 1:4; \nGálatas 4:4&#8211;7; \nTito 3:3&#8211;7; \nJuan 16:8; \nGálatas 3:13&#8211;14; \n1 Pedro 2:21&#8211;22; \nRomanos 10:17; \nLucas 17:5; \nMarcos 9:23&#8211;24; \nEfesios 2:5&#8211;10; \nRomanos 3:21&#8211;26; \nColosenses 1:13&#8211;14; \nRomanos 8:14&#8211;17; \nGálatas 3:26; \nJuan 3:3&#8211;8; \n1 Pedro 1:23; \nRomanos 12:2; \nHebreos 8:7&#8211;12; \nEzequiel 36:25&#8211;27; \n2 Pedro 1:3&#8211;4; \nRomanos 8:1&#8211;4; \nRomanos 5:6&#8211;10."]],
                              [Data newItem:@[@"Creciendo en Cristo",@"Por su muerte en la cruz Jesús triunfó sobre las fuerzas del mal. \n\nAquél que subyugó los espíritus demoníacos durante su ministerio terrenal ha quebrantado su poder y aseguró su destino final. \n\nLa victoria de Jesús nos da victoria sobre las fuerzas del mal que aún buscan controlarnos, mientras caminamos con él en paz, gozo y la seguridad de su amor. \n\nAhora el Espíritu Santo mora en nosotros y nos da fortaleza. \n\nContinuamente comprometidos con Jesús como nuestro Salvador y Señor, somos liberados de las cargas de nuestros actos pasados. \n\nYa no moramos más en la oscuridad, miedo de los poderes malignos, ignorancia y el sinsentido de nuestra anterior forma de vivir. \n\nEn esta nueva libertad en Jesús, somos llamados a crecer en la semejanza de su carácter, comunicándonos cada día con Él en oración, alimentándonos de su Palabra, meditando en ella y en su providencia, cantando alabanzas, reuniéndonos para adorar, y participando en la misión de la Iglesia. \n\nMientras nos damos a nosotros mismos en amoroso servicio hacia los que nos rodean y testimoniando acerca de su Salvación, su presencia constante con nosotros a través del Espíritu transforma cada momento y cada tarea en una experiencia espiritual.",@"Salmo 1:1&#8211;2; \nSalmo 23:4; \nSalmo 77:11&#8211;12; \nColosenses 1:13&#8211;14; \nColosenses 2:6, 14, 15; \nLucas 10:17&#8211;20; \nEfesios 5:19&#8211;20; \nEfesios 6:12&#8211;18; \n1 Tesalonicenses 5:23; \n2 Pedro 2:9; \n2 Pedro 3:18; \n2 Corintios 3:17&#8211;18; \nFilipenses 3:7&#8211;14; \n1 Tesalonicenses 5:16&#8211;18; \nMateo 20:25&#8211;28; \nJuan 20:21; \nGálatas 5:22&#8211;25; \nRomanos 8:38&#8211;39; \n1 Juan 4:4; \nHebreos 10:25."]],
                              ]],
                        @[@"Doctrina de la Iglesia?",
                          @[
                              [Data newItem:@[@"La Iglesia",@"La Iglesia es la comunidad de creyentes que confiesan a Jesucristo como Señor y Salvador. \n\nEn continuidad con el pueblo de Dios en los tiempos del Antiguo Testamento, somos llamados a salir del mundo; y nos unimos unimos para adorar, en fraternidad, para instrucción en la Palabra, para celebrar la Cena del Señor, para servir a toda la humanidad y para la proclamación mundial del Evangelio. \n\nLa autoridad de la Iglesia deriva de Cristo, quien es la Palabra encarnada, y de las Escrituras, que son la Palabra escrita. \n\nLa Iglesia es la familia de Dios, adoptados por Él como sus hijos e hijas. \n\nSus miembros viven fundamentados en el nuevo pacto. \n\nLa Iglesia es el cuerpo de Cristo, una comunidad de fe de quien Cristo mismo es la cabeza. \n\nLa iglesia es la esposa por la que Cristo murió para poder santificarla y limpiarla. \n\nEn su regreso triunfante, se la presentará a sí mismo como una iglesia gloriosa, la fiel de todas las épocas, la compra de su sangre, sin mancha ni arruga, sino santa y sin tacha.",@"Génesis 12:3; \nHechos 7:38; \nEfesios 4:11&#8211;15; \nEfesios 3:8&#8211;11; \nMateo 28:19&#8211;20; \nMateo 16:13&#8211;20; \nMateo 18:18; \nEfesios 2:19&#8211;22; \nEfesios 1:22&#8211;23; \nEfesios 5:23&#8211;27; \nColosenses 1:17&#8211;18."]],
                              [Data newItem:@[@"El Remaneciente y su Misión",@"La Iglesia universal se compone de todos los que verdaderamente creen en Cristo; pero, en los últimos días, en tiempo de extendida apostasía, ha sido llamado un remanente a fin de guardar los mandamientos de Dios y la fe de Jesús. \n\nEste remanente anuncia la llegada de la hora del Juicio, proclama la salvación por medio de Cristo y anuncia la proximidad de Su segundo advenimiento. \n\nEsta proclamación está simbolizada por los tres ángeles de Apocalipsis 14; coincide con la obra de juicio en el cielo, y trae como resultado el arrepentimiento y reforma sobre la Tierra. \n\nCada creyente es llamado a tener una parte en esta testificación mundial.",@"Apocalipsis 12:17; \nApocalipsis 14:6&#8211;12; \nApocalipsis 18:1&#8211;4; \n2 Corintios 5:10; \nJudas 1:3, 14; \n1 Pedro 1:16&#8211;19; \n2 Pedro 3:10&#8211;14; \nApocalipsis 21:1&#8211;14."]],
                              [Data newItem:@[@"Unidad en el Cuerpo de Cristo",@"La Iglesia es un cuerpo con muchos miembros, llamados de toda nación, tribu, lengua y pueblo. \n\nEn Cristo somos una nueva creación; las diferencias de raza, cultura, educación, y nacionalidad, y las diferencias entre clases, ricos y pobres, hombre y mujer, no deben ser divisorias entre nosotros. \n\nTodos somos iguales en Cristo, quien a través de un Espíritu nos ha unido en una fraternidad con Él y los unos con los otros; tenemos que servir y ser servidos imparcialmente y sin reservas. \n\nMediante la revelación de Jesucristo en las Escrituras, compartimos la misma fe y esperanza y extendemos un solo testimonio para todos. \n\nEsta unidad encuentra su fuente en la unidad del Dios trino y uno, que nos adoptó como Sus hijos.",@"Romanos 12:4&#8211;5; \n1 Corintios 12:12&#8211;14; \nMateo 28:19&#8211;20; \nSalmo 133:1; \n2 Corintios 5:16&#8211;17; \nHechos 17:26&#8211;27; \nGálatas 3:27&#8211;29; \nColosenses 3:10&#8211;15; \nEfesios 4:14&#8211;16; \nEfesios 4:1&#8211;6; \nJuan 17:20&#8211;23."]],
                              [Data newItem:@[@"El Bautismo",@"Por el bautismo confesamos nuestra fe en la muerte y en la resurrección de Jesucristo y testimoniamos nuestra muerte al pecado y nuestro propósito de andar en novedad de vida. \n\nDe este modo aceptamos a Cristo como nuestro Señor y Salvador, llegamos a pertenecer a su pueblo, y somos aceptados como miembros por Su Iglesia. \n\nEl bautismo es un símbolo de nuestra unión con Cristo, el perdón de nuestros pecados y nuestra recepción del Espíritu Santo. \n\nEs por inmersión en agua y es contingente sobre una afirmación de fe en Jesús y evidencia de arrepentimiento del pecado. \n\nTiene lugar tras la instrucción en las Santas Escrituras y la aceptación de sus enseñanzas.",@"Romanos 6:1&#8211;6; \nColosenses 2:12&#8211;13; \nHechos 16:30&#8211;33; \nHechos 22:16; \nHechos 2:38; \nMateo 28:19&#8211;20."]],
                              [Data newItem:@[@"La Cena del Señor",@"La Cena del Señor es una participación en los emblemas del cuerpo y de la sangre de Jesús, como expresión de fe en Él, nuestro Señor y Salvador. \n\nEn esta experiencia de comunión Cristo está presente para fortalecer su pueblo. \n\nAl participar, gozosamente proclamamos la muerte del Señor hasta que regrese de nuevo. \n\nLa preparación para la Cena incluye el examen de conciencia, arrepentimiento y confesión. \n\nEl Maestro instituyó la ceremonia del lavamiento de pies para representar una limpieza renovada, para expresar la disposición de servir unos a otros en humildad semejante a la de Cristo, y para unir nuestros corazones en amor. \n\nEl servicio de Comunión o Santa Cena está abierto a todos los cristianos creyentes.",@"1 Corintios 10:16&#8211;17; \n1 Corintios 11:23&#8211;30; \nMateo 26:17&#8211;30; \nApocalipsis 3:20; \nJuan 6:48&#8211;63; \nJuan 13:1&#8211;17."]],
                              [Data newItem:@[@"Dones y Ministerios Espirituales",@"Dios confiere a todos los miembros de su Iglesia, en todas las épocas, dones espirituales que cada miembro debe emplear en amante ministerio por el bien común de la Iglesia y de la humanidad. \n\nSiendo otorgados por la actuación del Espíritu Santo, el cual distribuye a cada miembro como quiere, los dones proveen todas las aptitudes y ministerios que la Iglesia necesita para cumplir sus funciones divinamente ordenadas. \n\nDe acuerdo con las Escrituras incluye tales ministerios como la fe, sanación, profecía, proclamación, enseñanza, administración, reconciliación, compasión, servicio abnegado, caridad para ayudar, y exhortación y aliento a las personas. \n\nAlgunos miembros son llamados por Dios y dotados por el Espíritu para funciones reconocidas por la Iglesia en ministerios pastorales, evangélicos, apostólicos y de enseñanza. Particularmente necesarios para capacitar a los miembros para el servicio, edificar a la iglesia para una madurez espiritual y fomentar la unidad de fe y el conocimiento de Dios. \n\nCuando los miembros emplean esos dones espirituales como fieles mayordomos de la variada gracia de Dios, la iglesia es protegida de la destructiva influencia de la falsa doctrina, tiene un crecimiento que proviene de Dios y es edificada con fe y amor.",@"Romanos 12:4&#8211;8; \n1 Corintios 12:9&#8211;11, 27&#8211;28; \nEfesios 4:8, 11&#8211;16; \nHechos 6:1&#8211;7; \n1 Timoteo 3:1&#8211;13; \n1 Pedro 4:10&#8211;11."]],
                              [Data newItem:@[@"El Don de Profecía",@"Uno de los dones del Espíritu Santo es el de profecía. \n\nEste don es una característica distintiva de la Iglesia remanente y fue manifestado en el ministerio de Ellen G. hite. \n\nComo mensajera del Señor, sus escritos son una continua y autorizada fuente de verdad y proporcionan consuelo, guía, instrucción y corrección a la Iglesia. \n\nSus escritos también dejan claro que la Biblia es la regla por la que debe ser probada toda enseñanza y experiencia.",@"Joel 2:28&#8211;29; \nHechos 2:14&#8211;21; \nHebreos 1:1&#8211;3; \nApocalipsis 12:17; \nApocalipsis 19:10."]],
                              [Data newItem:@[@"La Ley de Dios",@"Los grandes principios de la Ley de Dios están incluidos en los Diez Mandamientos y ejemplificados en la vida de Cristo. \n\nExpresan el amor, la voluntad y los propósitos de Dios respecto la conducta y relaciones humanas, y son vinculantes a todas las personas de todas las épocas. \n\nEsos preceptos constituyen la base del pacto de Dios con su pueblo y la norma en el juicio de Dios. \n\nA través de la intervención del Espíritu Santo, los Mandamientos señalan el pecado y despiertan el sentido de necesidad de un Salvador. \n\nLa Salvación es completamente por gracia y no por obras, pero el fruto de ella es la obediencia a los Mandamientos. \n\nEsta obediencia desarrolla el carácter cristiano y resulta en un sentido de bienestar. \n\nEs una evidencia de nuestro amor por el Señor y de nuestra preocupación por el prójimo. \n\nLa obediencia de fe demuestra el poder de Cristo para transformar vidas, y por lo tanto fortalece el testimonio cristiano.",@"Éxodo 20:1&#8211;17; \nSalmo 40:7&#8211;8; \nMateo 22:36&#8211;40; \nDeuteronomio 28:1&#8211;14; \nMateo 5:17&#8211;20; \nHebreos 8:8&#8211;19; \nJuan 15:7&#8211;10; \nEfesios 2:8&#8211;10; \n1 Juan 5:3; \nRomanos 8:3&#8211;4; \nSalmo 19:7&#8211;14."]],
                              [Data newItem:@[@"El Sábado",@"El bondadoso Creador, después de los seis días de la Creación, descansó el séptimo día e instituyó el Sábado para todo el mundo como recordativo de la Creación. \n\nEl cuarto mandamiento de la inmutable Ley de Dios requiere la observancia de este séptimo día sábado como día de descanso, adoración y ministerio en armonía con las enseñanzas y prácticas de Jesús, el Señor del Sábado. \n\nEl sábado es un día de agradable comunión con Dios y unos con otros. \n\nTambién es un símbolo de nuestra redención en Cristo, una señal de nuestra santificación, una demostración de nuestra lealtad, y un anticipo de nuestro futuro eterno en el reino de Dios. \n\nEl sábado es una señal perpetua de su pacto eterno entre Él y su pueblo. \n\nLa observancia gozosa de este santo tiempo de puesta de sol a puesta de sol o de tarde a tarde, es una celebración de los actos creativo y redentor de Dios.",@"Génesis 2:1&#8211;3; \nÉxodo 20:8&#8211;11; \nLucas 4:16; \nIsaías 56:5&#8211;6; \nIsaías 58:13&#8211;14; \nMateo 12:1&#8211;12; \nMarcos 2:27&#8211;28; \nÉxodo 31:13&#8211;17; \nEzequiel 20:12, 20; \nDeuteronomio 5:12&#8211;15; \nHebreos 4:1&#8211;11; \nLevítico 23:32; \nMarcos 1:32."]],
                              [Data newItem:@[@"Mayordomía",@"Somos mayordomos de Dios, quien nos ha encomendado el tiempo y las oportunidades, capacidades y posesiones, y las bendiciones de la Tierra y sus recursos. \n\nReconocemos la propiedad divina por medio del fiel servicio a Él y a nuestros semejantes, y devolviendo diezmos y dando ofrendas para la proclamación de su Evangelio y para la manutención y el crecimiento de su iglesia. \n\nLa mayordomía es un privilegio que nos ha dado Dios para crecer en amor y en victoria sobre el egoísmo y la codicia. \n\nEl mayordomo se regocija en las bendiciones que sobrevienen a los demás como resultado de su fidelidad.",@"Génesis 1:26&#8211;28; \nGénesis 2:15; \n1 Crónicas 29:14; \nHageo 1:3&#8211;11; \nMalaquías 3:8&#8211;12; \n1 Corintios 9:9&#8211;14; \nMateo 23:23; \n2 Corintios 8:1&#8211;15; \nRomanos 15:26&#8211;27."]],
                              [Data newItem:@[@"Conducta Cristiana",@"Somos llamados para ser un pueblo piadoso, que piensa, siente y actúa de acuerdo con los principios del Cielo. \n\nPara que el Espíritu recree en nosotros el carácter de nuestro Señor, nos involucramos sólo en aquellas cosas que producirán en nuestra vida pureza, salud y alegría semejantes a las de Cristo. \n\nEsto quiere decir que nuestra diversión y entretenimiento deberían cumplir la más alta norma del gusto y belleza cristianos. \n\nA la vez que reconocemos las diferencias culturales, nuestro vestido tiene que ser sencillo, modesto y pulcro, adecuándose aquellos cuya auténtica belleza no consiste en adorno externo sino en el incorruptible adorno de un espíritu tranquilo y afable. \n\nTambién significa que, dado que nuestro cuerpo es templo del Espíritu Santo, debemos cuidarlo de forma inteligente. \n\nCon ejercicio y descanso adecuados, debemos adoptar la dieta más saludable posible y abstenernos de alimentos inmundos identificados en las Escrituras. \n\nDado que el uso del bebidas alcohólicas, el tabaco, y el uso irresponsable de drogas y narcóticos son dañinos para nuestra salud, debemos de abstenernos de ellos. \n\nEn su lugar, debemos participar en cualquier cosa que eleve nuestros pensamientos y cuerpos a la disciplina de Cristo, quien desea nuestra salud completa, gozo y bienestar.",@"Romanos 12:1&#8211;2; \n1 Juan 2:6; \nEfesios 5:1&#8211;21; \nFilipenses 4:8; \n2 Corintios 10:5; \n2 Corintios 6:14&#8211;7:1; \n1 Pedro 3:1&#8211;4; \n1 Corintios 6:19&#8211;20; \n1 Corintios 10:31; \nLevítico 11:1&#8211;47; \n3 Juan 1:2."]],
                              [Data newItem:@[@"Matrimonio y Familia",@"El matrimonio fue divinamente establecido en el Edén y confirmado por Jesús como unión vitalicia entre un hombre y una mujer, en amoroso compañerismo. \n\nPara el cristiano, el compromiso matrimonial es con Dios así como con el cónyuge, y solamente debe ser asumido entre parejas que comparten la misma fe. \n\nEl amor mutuo, honor, respeto y responsabilidad son los elementos que edifican esta relación, que tiene que reflejar el amor, santidad, proximidad y permanencia de la relación entre Cristo y su Iglesia. \n\nRespecto al divorcio, Jesús enseñó que la persona que se divorcia del cónyuge, a no ser por causa de fornicación, y se casa con otro, comete adulterio. \n\nA pesar de que algunas relaciones familiares puedan no llegar al ideal, los cónyuges que se comprometen plenamente el uno al otro en Cristo, deben alcanzar la amorosa unidad con la guía del Espíritu Santo y los cuidados de la Iglesia. \n\nDios bendice la familia y quiere que sus miembros se ayuden unos a otros hasta alcanzar completa madurez. \n\nLos padres deben educar sus hijos para amar al Señor y obedecerle. \n\nPor su ejemplo y sus palabras tienen que enseñarles que Cristo disciplina con amor, siempre tierno y cariñoso, quien desea que se conviertan en miembros de su cuerpo, la familia de Dios. \n\nIncrementar la unión familiar es uno de los cometidos del mensaje final del Evangelio.",@"Génesis 2:18&#8211;25; \nMateo 19:3&#8211;9; \nJuan 2:1&#8211;11; \n2 Corintios 6:14; \nEfesios 5:21&#8211;33; \nMateo 5:31&#8211;32; \nMarcos 10:11&#8211;12; \nLucas 16:18; \n1 Corintios 7:10&#8211;11; \nÉxodo 20:12; \nEfesios 6:1&#8211;4; \nDeuteronomio 6:5&#8211;9; \nProverbios 22:6; \nMalaquías 4:5&#8211;6."]],
                              [Data newItem:@[@"El Ministerio de Cristo en el Santuario Celestial",@"Hay un santuario en el Cielo, el tabernáculo verdadero que levantó el Señor y no el hombre. \n\nEn él, Cristo intercede en nuestro favor, haciendo accesibles a los creyentes los beneficios de su sacrificio expiatorio ofrecido una vez para todos en la cruz. \n\nÉl es nuestro gran Sumo Sacerdote y comenzó su ministerio intercesor en ocasión de su ascensión. \n\nEn 1844, a final del período profético de los 2.300 días, inició la segunda y última fase de su ministerio expiatorio. \n\nEs una labor de juicio investigador que forma parte de la disposición final de todo pecado, tipificado por la purificación del antiguo santuario hebreo en el día de la Expiación. \n\nEn aquel servicio tipo el santuario era purificado con la sangre de sacrificios animales, pero las cosas celestiales son purificadas con el sacrificio perfecto de la sangre de Jesús. \n\nEl juicio investigador revela a las inteligencias celestiales quiénes de entre los muertos que duermen en Cristo y por lo tanto, en Él, son juzgados dignos de tener parte en la primera resurrección. \n\nTambién se hace manifiesto quiénes, de entre los vivos, están morando en Cristo, guardando los mandamientos de Dios y la fe de Jesús, y en Él, por lo tanto, están preparados para ser trasladados a su reino eterno. \n\nEste juicio vindica la justicia de Dios al salvar a aquellos que creen en Jesús. \n\nDeclara que aquellos que han permanecido fieles a Dios recibirán su reino. \n\nLa culminación de este ministerio de Cristo señalará el fin del tiempo de gracia para los seres humanos, antes del segundo advenimiento.",@"Hebreos 8:1&#8211;5; \nHebreos 4:14&#8211;16; \nHebreos 9:11&#8211;28; \nHebreos 10:19&#8211;22; \nHebreos 1:3; \nHebreos 2:16&#8211;17; \nDaniel 7:9&#8211;27; \nDaniel 8:13&#8211;14; \nDaniel 9:24&#8211;27; \nNúmeros 14:34; \nEzequiel 4:6; \nLevítico 16; \nApocalipsis 14:6&#8211;7; \nApocalipsis 20:12; \nApocalipsis 14:12; \nApocalipsis 22:12."]],
                              [Data newItem:@[@"La Segunda Venida de Cristo",@"La segunda venida de Cristo es la bendita esperanza de la Iglesia, el gran clímax del Evangelio. \n\nLa venida del Salvador será literal, personal, visible y global. \n\nCuando Él regrese, los muertos justos resucitarán, y junto a los vivos justos serán glorificados y tomados a los cielos, pero los injustos morirán. \n\nEl casi completo cumplimiento de la mayoría de profecías, junto con la presente condición del mundo, indican que la venida de Cristo es inminente. \n\nEl momento de ese evento no ha sido revelado, y por lo tanto se nos exhorta a estar preparados en todo momento.",@"Tito 2:13; \nHebreos 9:28; \nJuan 14:1&#8211;3; \nHechos 1:9&#8211;11; \nMateo 24:14; \nApocalipsis 1:7; \nMateo 24:43&#8211;44; \n1 Tesalonicenses 4:13&#8211;18; \n1 Corintios 15:51&#8211;54; \n2 Tesalonicenses 1:7&#8211;10; \n2 Tesalonicenses 2:8; \nApocalipsis 14:14&#8211;20; \nApocalipsis 19:11&#8211;21; \nMateo 24; \nMarcos 13; \nLucas 21; \n2 Timoteo 3:1&#8211;5; \n1 Tesalonicenses 5:1&#8211;6."]],
                              [Data newItem:@[@"Muerte y Resurrección",@"La paga del pecado es la muerte. \n\nPero Dios, el único que es inmortal, concederá vida eterna a sus redimidos. \n\nHasta aquel día, la muerte es un estado inconsciente para todas las personas. \n\nCuando Cristo, quien es nuestra vida, aparezca, los justos resucitados y los justos vivos serán glorificados y tomados para encontrarse con su Señor. \n\nLa segunda resurrección, la resurrección de los injustos, tendrá lugar mil años después.",@"Romanos 6:23; \n1 Timoteo 6:15&#8211;16; \nEclesiastés 9:5&#8211;6; \nSalmo 146:3&#8211;4; \nJuan 11:11&#8211;14; \nColosenses 3:4; \n1 Corintios 15:51&#8211;54; \n1 Tesalonicenses 4:13&#8211;17; \nJuan 5:28&#8211;29; \nApocalipsis 20:1&#8211;10."]],
                              [Data newItem:@[@"El Milenio y el Fin del Pecado",@"El milenio es el reinado de mil años de Cristo con sus santos en el Cielo entre la primera y la segunda resurrección. \n\nDurante este tiempo serán juzgados los impíos muertos; la Tierra estará completamente desolada, sin habitantes humanos vivos, aunque estará ocupada por Satanás y sus ángeles. \n\nAl fin de ese período, Cristo con sus Santos y la Santa Ciudad descenderán del cielo a la Tierra. \n\nLos impíos muertos serán entonces resucitados y, con Satanás y sus ángeles, cercarán la ciudad; pero el fuego de Dios los consumirá y purificará la Tierra. \n\nEl Universo será liberado para siempre del pecado y de los pecadores.",@"Apocalipsis 20; \n1 Corintios 6:2&#8211;3; \n2 Pedro 3:7; \nJeremías 4:23&#8211;26; \nApocalipsis 21:1&#8211;5; \nMalaquías 4:1; \nEzequiel 28:18&#8211;19."]],
                              [Data newItem:@[@"La Nueva Tierra",@"En la Nueva Tierra, en que habita la justicia, Dios proveerá un hogar eterno para los redimidos y un medio ambiente perfecto para la vida eterna, amor, gozo y aprendizaje en su presencia. \n\nPorque allí mismo morará Dios con su pueblo, y el sufrimiento y la muerte ya habrán pasado. \n\nLa gran controversia habrá llegado a su fin, y no habrá más pecado. \n\nTodas las cosas, animadas e inanimadas, declararán que Dios es amor; y Él reinará para siempre. \n\nAmén.",@"2 Pedro 3:13; \nIsaías 35; \nIsaías 65:17&#8211;25; \nMateo 5:5; \nApocalipsis 21:1&#8211;7; \nApocalipsis 22:1&#8211;5; \nApocalipsis: 11:15."]],
                              ]
                        ]
                    ];
    };
}

@end
